plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.141'
}


def offlineNeoForgeConfig = layout.projectDirectory.file("gradle/offline/neoforge-${neo_version}-moddev-config.json")
configurations.matching { it.name == 'neoForgeConfigOnly' }.all {
    withDependencies { dependencySet ->
        dependencySet.clear()
        dependencySet.add(project.dependencies.create(project.files(offlineNeoForgeConfig.asFile)))
    }
}

version = mod_version
group = mod_group_id

repositories {
    maven {
        name = 'ArmoredArsenalOffline'
        url = layout.projectDirectory.dir('gradle/offline-maven')
    }
}

base {
    archivesName = mod_id
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

neoForge {
    version = neo_version

    runs {
        client {
            client()
            programArgument '--username'
            programArgument 'ethan0315'
        }

        server {
            server()
            programArgument '--nogui'
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        armoredarsenal {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

processResources {
    def replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}
