pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'net.neoforged.moddev') {
                useModule("net.neoforged:moddev-gradle:${requested.version}")
            }
        }
    }

    repositories {
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases'
        }
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        maven {
            name = 'ArmoredArsenalOffline'
            url = uri('gradle/offline-maven')
        }
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases'
        }
        mavenCentral()
    }
}

rootProject.name = 'armored-arsenal'
